### ISSUE TITLE
Is it possible to change the polynomial degree?

### ISSUE THREAD

**Issue by fionser** [vernamlab/cuFHE#1]

**Comment by WeiDaiWD** [comment]
At this point, it is not possible and not reasonable to change the polynomial degree.
1. Degree 1024 is chosen in the TFHE paper. Decreasing it compromises security, while increasing it is less efficient.
2. Code in this library is optimized for degree 1024 only.

If you are only interested in accelerating polynomial arithmetic operations, the [cuHE ](https://github.com/vernamlab/cuHE) library supports larger polynomial degrees.
