### ISSUE TITLE
SIGSEGV for test_api_cpu

### ISSUE THREAD

**Issue by l4l** [vernamlab/cuFHE#7]
Building with `-g` flag (segfault is also w/o it, but also w/o symbols) causes sigsegv with the following output:

```
------ Key Generation ------
------ Test Encryption/Decryption ------
Number of tests:        1024
PASS
------ Test NAND Gate ------
Number of tests:        4
PASS

Program received signal SIGSEGV, Segmentation fault.
```

Debugger points out to that line:
https://github.com/vernamlab/cuFHE/blob/ec47abb56bc263e9b5ba1efae216b6e8bd90a753/cufhe/lib/cufhe.cc#L288

Where `lwe_sample_device_` is nullptr

p.s. thanks for your amazing work!

**Comment by gizemscetin** [comment]
Thanks for pointing that out! It's fixed now.
