### ISSUE TITLE
Use of private key to encrypt

### ISSUE THREAD

**Issue by munsanje** [vernamlab/cuFHE#9]
It seems this library uses the private key to encrypt data. Shouldn't this be happening with the public key or am I missing something?

**Comment by benediamond** [comment]
I agree that this is unusual. any thoughts?

**Comment by benediamond** [comment]
@munsanje one workaround is for the holder of the private key to simply publish encryptions of 0 and 1 (and identify them as such). since these are the only plaintexts, they can be re-used by external parties.
